name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }} # so PRs resolve to correct branch
          fetch-depth: 0 # needed for only_changed below
          persist-credentials: false
      - run: git config --global user.name "prettier[bot]" && git config --global user.email "8818390+kvanzuijlen@users.noreply.github.com"
      - name: Prettify code
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          commit_message: "Prettier"
          only_changed: True
          github_token: ${{ secrets.TODO }}
          prettier_options: --write . # the . targets all files which prettier _can_ parse, and ignores all others
