name: Create release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
      pull-requests: "read"
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: VERSION=${{ steps.draft_release.outputs.tag_name }} make docker-push

      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        if: steps.draft_release.outputs.tag_name != ''
        with:
          version: ${{ steps.draft_release.outputs.tag_name }}
          publish: true
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
